### ISSUE TITLE
about firmware

### ISSUE THREAD

**Issue by charleyzhu** [klouderone/cornev4promicroedition#6]
Hello, I am currently using the RP2040 Pro Micro module. After uploading the firmware to the left keyboard, it always stays in the bootloader and cannot load the firmware properly. The right keyboard's LED is displaying content. What could be the issue? Also, is this firmware open source?

**Comment by klouderone** [comment]
Firmware is open source, and is under Corne on ZMK, QMK and QMK-VIAL. The precompiled firmware is proven to work, and is added as a quick check to make sure everything works as intended. Sounds like a microcontroller problem?

**Comment by klouderone** [comment]
How are you writing to the RP2040? Are you entering the bootloader by double clicking the reset button, and then dragging the UF2 file into the controller on your file explorer? I am not sure what the problem would be other than the microcontroller or the correct flashing method.

**Comment by charleyzhu** [comment]
> How are you writing to the RP2040? Are you entering the bootloader by double clicking the reset button, and then dragging the UF2 file into the controller on your file explorer? I am not sure what the problem would be other than the microcontroller or the correct flashing method.

I’m sure I’m writing the firmware correctly, and I’m also considering the controller issue. I’ve purchased two RP2040 boards with 16M Flash (the current Flash size is 4M). I’ll try writing the firmware again once they arrive tomorrow.

**Comment by jerlam06** [comment]
@charleyzhu Did you solve the issue? I encounter the same problem.

**Comment by jerlam06** [comment]
Edit: so it turns out I was building the firmware wrongly. This is what worked for me:
`
# Build LEFT side
make crkbd/rev1:default:uf2-split-left CONVERT_TO=promicro_rp2040

# Build RIGHT side  
make crkbd/rev1:default:uf2-split-right CONVERT_TO=promicro_rp2040`
