### ISSUE TITLE
SVG files

### ISSUE THREAD

**Issue by SparrowMike** [klouderone/cornev4promicroedition#7]
Hey!

Thanks for sharing this cool project, I was wondering if you have svg files for the screen covers as I would like to cut some instead of using 3D printed.

Many thanks!

Cheers

**Comment by klouderone** [comment]
done, they are located under cases/oled covers. you will need some taller standoffs (around 10mm to 11mm) than 7mm ones though as the acrylic is flat and the 3D printed ones are not!

**Comment by klouderone** [comment]
Hm, strange. I'll upload as a DXF as that'll have proper scaling, I'm not the biggest fan of SVG's

**Comment by cuongha0701** [comment]
> done, they are located under cases/oled covers. you will need some taller standoffs (around 10mm to 11mm) than 7mm ones though as the acrylic is flat and the 3D printed ones are not!

Hi, can you please upload acrylic oled cover in Kicad format?
